[tool.poetry]
name = "bookingroomsservice"
version = "0.1.0"
description = ""
authors = ["goormany <zarbot351@yandex.ru>"]
readme = "README.md"
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = ">=3.12,<4.0"
fastapi = ">=0.139.0,<0.140.0"
sqlalchemy = ">=2.0.51,<3.0.0"
pydantic = ">=2.13.4,<3.0.0"
pydantic-settings = ">=2.14.2,<3.0.0"
asyncpg = ">=0.31.0,<0.32.0"
alembic = ">=1.18.5,<2.0.0"
uvicorn = { version = ">=0.51.0,<0.52.0", extras = ["standard"] }
python-multipart = ">=0.0.32,<0.0.33"
pyjwt = ">=2.13.0,<3.0.0"
pwdlib = { version = ">=0.3.0,<0.4.0", extras = ["argon2"] }
redis = ">=8.0.1,<9.0.0"
httpx = ">=0.28.1,<0.29.0"
python-dotenv = ">=1.2.2,<2.0.0"
black = ">=26.5.1,<27.0.0"
pytest = ">=9.1.1,<10.0.0"
pytest-asyncio = ">=1.4.0,<2.0.0"
ruff = "^0.15.22"
asgi-lifespan = "==2.*"
fastapi-cache2 = "^0.2.2"
jinja2 = "^3.1.6"
pytest-dotenv = "^0.5.2"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff.lint.per-file-ignores]
"src/models/*.py" = ["F821"]